#include "stdio.h"

[!c] {
    int sum(int a, int b) {
        return a + b;
    }
}

fn main() : int {
    var number : int = 10;
    printf("hell yeah\n");
    da
    match (number) {
        case 5 || 6 -> {
            printf("number is 5 or 6\n");
        }
        case 0 || 2 -> {
            printf("number is 0 or 2\n");
        }
        default -> {
            printf("idk\n")
        }
    }
}
